/* oxlint-disable react/only-export-components -- Provider and hook intentionally share one context module. */
import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type Language = "en" | "it" | "fr" | "es";
type Copy = { nav: string[]; role: string; intro: string; availability: string; contactMe: string; work: string; selected: string; live: string; code: string; aboutLabel: string; about: string; contactLabel: string; letsTalk: string; blurbs: string[] };

const translations: Record<Language, Copy> = {
  en: { nav: ["Work", "About", "Contact"], role: "Software & Full-Stack Developer", intro: "Software developer at École 42 Marseille — solid in C/C++, Python and full-stack web, with project work in applied AI, optimisation and cybersecurity.", availability: "Seeking an apprenticeship or internship in software development from November 2026", contactMe: "Contact me", work: "Work", selected: "2025 — selected", live: "Live", code: "Code", aboutLabel: "/ about", about: "Software developer training at École 42 Marseille, with solid foundations in C/C++, Python and full-stack development. I’ve worked on concrete projects across applied AI, optimisation and cybersecurity — and I like to stay close to the system, from the interface down to the container. Autonomous and rigorous, at ease in an international team.", contactLabel: "/ contact", letsTalk: "Let’s talk", blurbs: ["A fully containerised infrastructure built from scratch for École 42: NGINX with TLS, WordPress and MariaDB in separate images, orchestrated with Docker Compose and hand-written Dockerfiles. Source stays private under École 42’s policy — I can walk through the architecture.", "École 42 systems and algorithms projects — Libft (a C standard-library reimplementation), Push_swap (sorting with a minimal instruction set), plus Python work on multithreading, RAG and constrained decoding. Source stays private under École 42’s policy.", "Heat-aware pedestrian routing for Marseille — a 3D point-cloud model that finds the coolest walking path on a hot day.", "Upload a portfolio spreadsheet and get a full risk-and-allocation breakdown plus a polished Excel report.", "The arcade classic written in Python, compiled to WebAssembly and running in the browser at native speed — no server, no install.", "An earlier take on this site: a navigable galaxy where each star system is a project, built with React Three Fiber.", "The pipeline behind these projects: a git push builds a Docker image and Traefik serves it on its own HTTPS subdomain.", "Solutions from SANS capture-the-flag events — reversing, pwn, web and crypto — collected as sanitised notes.", "Client project with CMA CGM and Mistral AI (hackathon). Details are confidential — happy to walk through it in an interview.", "Client project with CMA CGM (graph-theory workshop). Details are confidential — happy to walk through it in an interview.", "A mosquito-risk prediction platform for Qista, a mosquito-trap company (started at a ZEBOX hackathon, pitched to investors). Three Dockerised services — a map UI, an Express gateway and a FastAPI engine — score locations across France 0–100 from live weather, seasonality and environment type."] },
  it: { nav: ["Progetti", "Chi sono", "Contatti"], role: "Sviluppatore Software & Full-Stack", intro: "Sviluppatore software alla École 42 di Marsiglia — solide basi in C/C++, Python e web full-stack, con progetti su IA applicata, ottimizzazione e cybersecurity.", availability: "Cerco un’alternanza o uno stage in sviluppo software da novembre 2026", contactMe: "Contattami", work: "Progetti", selected: "2025 — selezione", live: "Online", code: "Codice", aboutLabel: "/ chi sono", about: "Sviluppatore software in formazione alla École 42 di Marsiglia, con solide basi in C/C++, Python e sviluppo full-stack. Ho lavorato su progetti concreti tra IA applicata, ottimizzazione e cybersecurity — e mi piace restare vicino al sistema, dall’interfaccia fino al container. Autonomo e rigoroso, a mio agio in un team internazionale.", contactLabel: "/ contatti", letsTalk: "Parliamone", blurbs: ["Un’infrastruttura interamente containerizzata costruita da zero per la École 42: NGINX con TLS, WordPress e MariaDB in immagini separate, orchestrate con Docker Compose e Dockerfile scritti a mano. Il codice resta privato per policy della École 42 — posso spiegare l’architettura.", "Progetti di sistemi e algoritmi della École 42 — Libft (reimplementazione della libreria standard C), Push_swap (ordinamento con un set minimo di istruzioni), più lavoro in Python su multithreading, RAG e constrained decoding. Il codice resta privato per policy della École 42.", "Percorsi pedonali sensibili al calore per Marsiglia — un modello 3D della città che individua il tragitto più fresco nelle giornate calde.", "Carica il foglio di calcolo di un portafoglio e ottieni un’analisi completa di rischio e allocazione con un report Excel professionale.", "Il classico arcade scritto in Python, compilato in WebAssembly e utilizzabile nel browser a velocità nativa — senza server né installazione.", "Una precedente versione di questo sito: una galassia navigabile in cui ogni sistema stellare rappresenta un progetto.", "La pipeline alla base di questi progetti: un push Git crea un’immagine Docker e Traefik la pubblica su un sottodominio HTTPS dedicato.", "Soluzioni delle capture-the-flag SANS — reversing, pwn, web e crittografia — raccolte in appunti ripuliti e condivisibili.", "Progetto per cliente con CMA CGM e Mistral AI (hackathon). I dettagli sono riservati — volentieri ne parlo in un colloquio.", "Progetto per cliente con CMA CGM (workshop di teoria dei grafi). I dettagli sono riservati — volentieri ne parlo in un colloquio.", "Una piattaforma di previsione del rischio zanzare per Qista, azienda di trappole per zanzare (nata a un hackathon ZEBOX, presentata agli investitori). Tre servizi in Docker — una UI mappa, un gateway Express e un motore FastAPI — assegnano a località in tutta la Francia un punteggio 0–100 da meteo in tempo reale, stagionalità e tipo di ambiente."] },
  fr: { nav: ["Projets", "À propos", "Contact"], role: "Développeur Logiciel & Full-Stack", intro: "Développeur en formation à l’École 42 Marseille — bases solides en C/C++, Python et web full-stack, avec des projets en IA appliquée, optimisation et cybersécurité.", availability: "Recherche une alternance ou un stage en développement logiciel à partir de novembre 2026", contactMe: "Me contacter", work: "Projets", selected: "2025 — sélection", live: "En ligne", code: "Code", aboutLabel: "/ à propos", about: "Développeur en formation à l’École 42 Marseille, avec de solides bases en C/C++, Python et développement full-stack. J’ai mené des projets concrets en IA appliquée, optimisation et cybersécurité — et j’aime rester proche du système, de l’interface au conteneur. Autonome et rigoureux, à l’aise en équipe internationale.", contactLabel: "/ contact", letsTalk: "Parlons-en", blurbs: ["Une infrastructure entièrement conteneurisée construite de zéro pour l’École 42 : NGINX avec TLS, WordPress et MariaDB dans des images séparées, orchestrées avec Docker Compose et des Dockerfiles écrits à la main. Le code reste privé selon la politique de l’École 42 — je peux détailler l’architecture.", "Projets systèmes et algorithmes de l’École 42 — Libft (réimplémentation de la bibliothèque standard C), Push_swap (tri avec un jeu d’instructions minimal), ainsi qu’un travail en Python sur le multithreading, le RAG et le constrained decoding. Le code reste privé selon la politique de l’École 42.", "Itinéraires piétons adaptés à la chaleur à Marseille — un modèle 3D de la ville qui trouve le trajet le plus frais lors des journées chaudes.", "Importez un portefeuille et obtenez une analyse complète du risque et de l’allocation, accompagnée d’un rapport Excel professionnel.", "Le classique de l’arcade écrit en Python, compilé en WebAssembly et exécuté dans le navigateur — sans serveur ni installation.", "Une version antérieure de ce site : une galaxie navigable où chaque système stellaire représente un projet.", "La pipeline derrière ces projets : un push Git construit une image Docker que Traefik publie sur son propre sous-domaine HTTPS.", "Solutions des capture-the-flag SANS — reverse engineering, pwn, web et cryptographie — réunies sous forme de notes épurées.", "Projet client avec CMA CGM et Mistral AI (hackathon). Les détails sont confidentiels — je peux en parler lors d’un entretien.", "Projet client avec CMA CGM (atelier de théorie des graphes). Les détails sont confidentiels — je peux en parler lors d’un entretien.", "Une plateforme de prédiction du risque moustiques pour Qista, fabricant de pièges à moustiques (née lors d’un hackathon ZEBOX, présentée à des investisseurs). Trois services Docker — une UI carte, une passerelle Express et un moteur FastAPI — attribuent à des localités partout en France un score de 0 à 100 à partir de la météo en temps réel, de la saisonnalité et du type d’environnement."] },
  es: { nav: ["Proyectos", "Sobre mí", "Contacto"], role: "Desarrollador de Software & Full-Stack", intro: "Desarrollador en formación en la École 42 Marsella — base sólida en C/C++, Python y web full-stack, con proyectos de IA aplicada, optimización y ciberseguridad.", availability: "Busco un contrato en alternancia o unas prácticas en desarrollo de software a partir de noviembre de 2026", contactMe: "Contáctame", work: "Proyectos", selected: "2025 — selección", live: "Ver online", code: "Código", aboutLabel: "/ sobre mí", about: "Desarrollador de software en formación en la École 42 Marsella, con bases sólidas en C/C++, Python y desarrollo full-stack. He trabajado en proyectos concretos de IA aplicada, optimización y ciberseguridad — y me gusta mantenerme cerca del sistema, desde la interfaz hasta el contenedor. Autónomo y riguroso, cómodo en un equipo internacional.", contactLabel: "/ contacto", letsTalk: "Hablemos", blurbs: ["Una infraestructura totalmente contenedizada creada desde cero para la École 42: NGINX con TLS, WordPress y MariaDB en imágenes separadas, orquestadas con Docker Compose y Dockerfiles propios. El código es privado por la política de la École 42 — puedo explicar la arquitectura.", "Proyectos de sistemas y algoritmos de la École 42 — Libft (reimplementación de la biblioteca estándar de C), Push_swap (ordenación con un conjunto mínimo de instrucciones), además de trabajo en Python sobre multithreading, RAG y constrained decoding. El código es privado por la política de la École 42.", "Rutas peatonales adaptadas al calor en Marsella — un modelo 3D de la ciudad que encuentra el trayecto más fresco en días calurosos.", "Sube una cartera y obtén un análisis completo de riesgo y asignación, junto con un informe profesional en Excel.", "El clásico arcade escrito en Python, compilado a WebAssembly y ejecutado en el navegador — sin servidor ni instalación.", "Una versión anterior de este sitio: una galaxia navegable donde cada sistema estelar representa un proyecto.", "El pipeline detrás de estos proyectos: un push de Git crea una imagen Docker y Traefik la publica en su propio subdominio HTTPS.", "Soluciones de los capture-the-flag de SANS — reversing, pwn, web y criptografía — reunidas como notas depuradas.", "Proyecto de cliente con CMA CGM y Mistral AI (hackathon). Los detalles son confidenciales — encantado de explicarlo en una entrevista.", "Proyecto de cliente con CMA CGM (taller de teoría de grafos). Los detalles son confidenciales — encantado de explicarlo en una entrevista.", "Una plataforma de predicción del riesgo de mosquitos para Qista, fabricante de trampas para mosquitos (nacida en un hackathon ZEBOX, presentada a inversores). Tres servicios Docker — una UI de mapa, una pasarela Express y un motor FastAPI — asignan a localidades de toda Francia una puntuación de 0–100 a partir del tiempo en tiempo real, la estacionalidad y el tipo de entorno."] },
};

function detectLanguage(): Language {
  const saved = localStorage.getItem("portfolio-language");
  if (saved === "en" || saved === "it" || saved === "fr" || saved === "es") return saved;

  const supported: Language[] = ["fr", "it", "es"];
  const detected = navigator.languages
    .map((locale) => locale.toLowerCase().split("-")[0])
    .find((locale): locale is Language => supported.includes(locale as Language));
  return detected ?? "en";
}

const I18nContext = createContext<{ language: Language; setLanguage: (value: Language) => void; copy: Copy } | null>(null);

export function I18nProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(detectLanguage);
  useEffect(() => { localStorage.setItem("portfolio-language", language); document.documentElement.lang = language; }, [language]);
  return <I18nContext value={{ language, setLanguage, copy: translations[language] }}>{children}</I18nContext>;
}

export function useI18n() {
  const value = useContext(I18nContext);
  if (!value) throw new Error("useI18n must be used inside I18nProvider");
  return value;
}
