/* oxlint-disable react/only-export-components -- Provider and hook intentionally share one context module. */
import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type Language = "en" | "it" | "fr" | "es";
type Copy = { nav: string[]; role: string; intro: string; availability: string; contactMe: string; work: string; selected: string; live: string; code: string; aboutLabel: string; about: string; contactLabel: string; letsTalk: string; blurbs: string[] };

const translations: Record<Language, Copy> = {
  en: { nav: ["Work", "About", "Contact"], role: "Full-Stack Developer · Creative Coder", intro: "I build things end-to-end — from the interface down to the container. Fast frontends, clean APIs, pipelines that just work.", availability: "Available for freelance & contract work", contactMe: "Contact me", work: "Work", selected: "2025 — selected", live: "Live", code: "Code", aboutLabel: "/ about", about: "Full-stack developer with a background in cybersecurity, I build web applications and the infrastructure that runs them — from the interface down to the container. I enjoy working close to the system: fast frontends, clean APIs, and deploy pipelines that just work. Let’s build something solid together!", contactLabel: "/ contact", letsTalk: "Let’s talk", blurbs: ["Heat-aware pedestrian routing for Marseille — a 3D point-cloud model that finds the coolest walking path on a hot day.", "Upload a portfolio spreadsheet and get a full risk-and-allocation breakdown plus a polished Excel report.", "The arcade classic written in Python, compiled to WebAssembly and running in the browser at native speed — no server, no install.", "An earlier take on this site: a navigable galaxy where each star system is a project, built with React Three Fiber.", "The pipeline behind these projects: a git push builds a Docker image and Traefik serves it on its own HTTPS subdomain.", "Solutions from SANS capture-the-flag events — reversing, pwn, web and crypto — collected as sanitised notes."] },
  it: { nav: ["Progetti", "Chi sono", "Contatti"], role: "Sviluppatore Full-Stack · Creative Coder", intro: "Realizzo prodotti completi — dall’interfaccia fino al container. Frontend veloci, API pulite e pipeline che funzionano davvero.", availability: "Disponibile per collaborazioni freelance e contratti", contactMe: "Contattami", work: "Progetti", selected: "2025 — selezione", live: "Online", code: "Codice", aboutLabel: "/ chi sono", about: "Sviluppatore full-stack con un background in cybersecurity, realizzo applicazioni web e l’infrastruttura che le sostiene — dall’interfaccia fino al container. Mi piace lavorare vicino al sistema: frontend veloci, API pulite e pipeline di deploy affidabili. Costruiamo insieme qualcosa di solido!", contactLabel: "/ contatti", letsTalk: "Parliamone", blurbs: ["Percorsi pedonali sensibili al calore per Marsiglia — un modello 3D della città che individua il tragitto più fresco nelle giornate calde.", "Carica il foglio di calcolo di un portafoglio e ottieni un’analisi completa di rischio e allocazione con un report Excel professionale.", "Il classico arcade scritto in Python, compilato in WebAssembly e utilizzabile nel browser a velocità nativa — senza server né installazione.", "Una precedente versione di questo sito: una galassia navigabile in cui ogni sistema stellare rappresenta un progetto.", "La pipeline alla base di questi progetti: un push Git crea un’immagine Docker e Traefik la pubblica su un sottodominio HTTPS dedicato.", "Soluzioni delle capture-the-flag SANS — reversing, pwn, web e crittografia — raccolte in appunti ripuliti e condivisibili."] },
  fr: { nav: ["Projets", "À propos", "Contact"], role: "Développeur Full-Stack · Creative Coder", intro: "Je conçois des produits de bout en bout — de l’interface au conteneur. Frontends rapides, API propres et pipelines fiables.", availability: "Disponible pour des missions freelance et des contrats", contactMe: "Me contacter", work: "Projets", selected: "2025 — sélection", live: "En ligne", code: "Code", aboutLabel: "/ à propos", about: "Développeur full-stack issu de la cybersécurité, je conçois des applications web et l’infrastructure qui les fait fonctionner — de l’interface au conteneur. J’aime les frontends rapides, les API propres et les pipelines fiables. Construisons quelque chose de solide !", contactLabel: "/ contact", letsTalk: "Parlons-en", blurbs: ["Itinéraires piétons adaptés à la chaleur à Marseille — un modèle 3D de la ville qui trouve le trajet le plus frais lors des journées chaudes.", "Importez un portefeuille et obtenez une analyse complète du risque et de l’allocation, accompagnée d’un rapport Excel professionnel.", "Le classique de l’arcade écrit en Python, compilé en WebAssembly et exécuté dans le navigateur — sans serveur ni installation.", "Une version antérieure de ce site : une galaxie navigable où chaque système stellaire représente un projet.", "La pipeline derrière ces projets : un push Git construit une image Docker que Traefik publie sur son propre sous-domaine HTTPS.", "Solutions des capture-the-flag SANS — reverse engineering, pwn, web et cryptographie — réunies sous forme de notes épurées."] },
  es: { nav: ["Proyectos", "Sobre mí", "Contacto"], role: "Desarrollador Full-Stack · Creative Coder", intro: "Creo productos de principio a fin — desde la interfaz hasta el contenedor. Frontends rápidos, API limpias y pipelines fiables.", availability: "Disponible para proyectos freelance y contratos", contactMe: "Contáctame", work: "Proyectos", selected: "2025 — selección", live: "Ver online", code: "Código", aboutLabel: "/ sobre mí", about: "Desarrollador full-stack con experiencia en ciberseguridad, creo aplicaciones web y la infraestructura que las mantiene — desde la interfaz hasta el contenedor. Me gustan los frontends rápidos, las API limpias y los pipelines fiables. ¡Construyamos algo sólido!", contactLabel: "/ contacto", letsTalk: "Hablemos", blurbs: ["Rutas peatonales adaptadas al calor en Marsella — un modelo 3D de la ciudad que encuentra el trayecto más fresco en días calurosos.", "Sube una cartera y obtén un análisis completo de riesgo y asignación, junto con un informe profesional en Excel.", "El clásico arcade escrito en Python, compilado a WebAssembly y ejecutado en el navegador — sin servidor ni instalación.", "Una versión anterior de este sitio: una galaxia navegable donde cada sistema estelar representa un proyecto.", "El pipeline detrás de estos proyectos: un push de Git crea una imagen Docker y Traefik la publica en su propio subdominio HTTPS.", "Soluciones de los capture-the-flag de SANS — reversing, pwn, web y criptografía — reunidas como notas depuradas."] },
};

function detectLanguage(): Language {
  const saved = localStorage.getItem("portfolio-language");
  if (saved === "en" || saved === "it" || saved === "fr" || saved === "es") return saved;

  const supported: Language[] = ["fr", "it", "es"];
  const detected = navigator.languages
    .map((locale) => locale.toLowerCase().split("-")[0])
    .find((locale): locale is Language => supported.includes(locale as Language));
  return detected ?? "en";
}

const I18nContext = createContext<{ language: Language; setLanguage: (value: Language) => void; copy: Copy } | null>(null);

export function I18nProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(detectLanguage);
  useEffect(() => { localStorage.setItem("portfolio-language", language); document.documentElement.lang = language; }, [language]);
  return <I18nContext value={{ language, setLanguage, copy: translations[language] }}>{children}</I18nContext>;
}

export function useI18n() {
  const value = useContext(I18nContext);
  if (!value) throw new Error("useI18n must be used inside I18nProvider");
  return value;
}
